### ISSUE TITLE
install without use composer

### ISSUE THREAD

**Issue by info2000** [jamm/Memory#10]
Hi, is possible install without use composer?
Thanks

**Comment by jamm** [comment]
Just download it, unpack and use. PSR-0 namespaces here, so you can use any autoloader you want to include files once. For example - https://github.com/jamm/Memory/blob/master/vendors/Jamm/Autoload/Autoloader.php, or https://github.com/jamm/Autoload/tree/master/lib/Jamm, or Composer's autoloader - any.
